// Minimal country name → ISO-A2 / ISO-A3 lookup for Jetpack-style stats.
// Handles the most common aliases (incl. Jetpack's "Hong Kong SAR China").

const NAME_TO_ISO: Record<string, { a2: string; a3: string }> = {
  "united states": { a2: "US", a3: "USA" },
  "united states of america": { a2: "US", a3: "USA" },
  "usa": { a2: "US", a3: "USA" },
  "canada": { a2: "CA", a3: "CAN" },
  "mexico": { a2: "MX", a3: "MEX" },
  "united kingdom": { a2: "GB", a3: "GBR" },
  "uk": { a2: "GB", a3: "GBR" },
  "great britain": { a2: "GB", a3: "GBR" },
  "ireland": { a2: "IE", a3: "IRL" },
  "france": { a2: "FR", a3: "FRA" },
  "germany": { a2: "DE", a3: "DEU" },
  "spain": { a2: "ES", a3: "ESP" },
  "portugal": { a2: "PT", a3: "PRT" },
  "italy": { a2: "IT", a3: "ITA" },
  "netherlands": { a2: "NL", a3: "NLD" },
  "belgium": { a2: "BE", a3: "BEL" },
  "switzerland": { a2: "CH", a3: "CHE" },
  "austria": { a2: "AT", a3: "AUT" },
  "sweden": { a2: "SE", a3: "SWE" },
  "norway": { a2: "NO", a3: "NOR" },
  "denmark": { a2: "DK", a3: "DNK" },
  "finland": { a2: "FI", a3: "FIN" },
  "iceland": { a2: "IS", a3: "ISL" },
  "poland": { a2: "PL", a3: "POL" },
  "czechia": { a2: "CZ", a3: "CZE" },
  "czech republic": { a2: "CZ", a3: "CZE" },
  "slovakia": { a2: "SK", a3: "SVK" },
  "hungary": { a2: "HU", a3: "HUN" },
  "romania": { a2: "RO", a3: "ROU" },
  "bulgaria": { a2: "BG", a3: "BGR" },
  "greece": { a2: "GR", a3: "GRC" },
  "serbia": { a2: "RS", a3: "SRB" },
  "croatia": { a2: "HR", a3: "HRV" },
  "slovenia": { a2: "SI", a3: "SVN" },
  "bosnia and herzegovina": { a2: "BA", a3: "BIH" },
  "albania": { a2: "AL", a3: "ALB" },
  "ukraine": { a2: "UA", a3: "UKR" },
  "russia": { a2: "RU", a3: "RUS" },
  "russian federation": { a2: "RU", a3: "RUS" },
  "turkey": { a2: "TR", a3: "TUR" },
  "türkiye": { a2: "TR", a3: "TUR" },
  "israel": { a2: "IL", a3: "ISR" },
  "saudi arabia": { a2: "SA", a3: "SAU" },
  "united arab emirates": { a2: "AE", a3: "ARE" },
  "uae": { a2: "AE", a3: "ARE" },
  "iran": { a2: "IR", a3: "IRN" },
  "iraq": { a2: "IQ", a3: "IRQ" },
  "egypt": { a2: "EG", a3: "EGY" },
  "south africa": { a2: "ZA", a3: "ZAF" },
  "nigeria": { a2: "NG", a3: "NGA" },
  "kenya": { a2: "KE", a3: "KEN" },
  "morocco": { a2: "MA", a3: "MAR" },
  "algeria": { a2: "DZ", a3: "DZA" },
  "ethiopia": { a2: "ET", a3: "ETH" },
  "india": { a2: "IN", a3: "IND" },
  "pakistan": { a2: "PK", a3: "PAK" },
  "bangladesh": { a2: "BD", a3: "BGD" },
  "sri lanka": { a2: "LK", a3: "LKA" },
  "china": { a2: "CN", a3: "CHN" },
  "hong kong": { a2: "HK", a3: "HKG" },
  "hong kong sar china": { a2: "HK", a3: "HKG" },
  "macao": { a2: "MO", a3: "MAC" },
  "macao sar china": { a2: "MO", a3: "MAC" },
  "taiwan": { a2: "TW", a3: "TWN" },
  "japan": { a2: "JP", a3: "JPN" },
  "south korea": { a2: "KR", a3: "KOR" },
  "korea, south": { a2: "KR", a3: "KOR" },
  "north korea": { a2: "KP", a3: "PRK" },
  "vietnam": { a2: "VN", a3: "VNM" },
  "thailand": { a2: "TH", a3: "THA" },
  "philippines": { a2: "PH", a3: "PHL" },
  "indonesia": { a2: "ID", a3: "IDN" },
  "malaysia": { a2: "MY", a3: "MYS" },
  "singapore": { a2: "SG", a3: "SGP" },
  "australia": { a2: "AU", a3: "AUS" },
  "new zealand": { a2: "NZ", a3: "NZL" },
  "brazil": { a2: "BR", a3: "BRA" },
  "argentina": { a2: "AR", a3: "ARG" },
  "chile": { a2: "CL", a3: "CHL" },
  "colombia": { a2: "CO", a3: "COL" },
  "peru": { a2: "PE", a3: "PER" },
  "venezuela": { a2: "VE", a3: "VEN" },
  "uruguay": { a2: "UY", a3: "URY" },
  "ecuador": { a2: "EC", a3: "ECU" },
  "bolivia": { a2: "BO", a3: "BOL" },
  "paraguay": { a2: "PY", a3: "PRY" },
  "cuba": { a2: "CU", a3: "CUB" },
};

export function lookupCountryISO(name: string): { a2: string; a3: string } | null {
  if (!name) return null;
  const key = name.trim().toLowerCase();
  return NAME_TO_ISO[key] ?? null;
}

// ISO-A2 → UN M49 numeric code (as 3-digit string) — used to match
// `world-atlas` topojson features whose `geo.id` is the M49 code.
export const A2_TO_M49: Record<string, string> = {
  US: "840", CA: "124", MX: "484", GB: "826", IE: "372", FR: "250", DE: "276",
  ES: "724", PT: "620", IT: "380", NL: "528", BE: "056", CH: "756", AT: "040",
  SE: "752", NO: "578", DK: "208", FI: "246", IS: "352", PL: "616", CZ: "203",
  SK: "703", HU: "348", RO: "642", BG: "100", GR: "300", RS: "688", HR: "191",
  SI: "705", BA: "070", AL: "008", UA: "804", RU: "643", TR: "792", IL: "376",
  SA: "682", AE: "784", IR: "364", IQ: "368", EG: "818", ZA: "710", NG: "566",
  KE: "404", MA: "504", DZ: "012", ET: "231", IN: "356", PK: "586", BD: "050",
  LK: "144", CN: "156", HK: "344", MO: "446", TW: "158", JP: "392", KR: "410",
  KP: "408", VN: "704", TH: "764", PH: "608", ID: "360", MY: "458", SG: "702",
  AU: "036", NZ: "554", BR: "076", AR: "032", CL: "152", CO: "170", PE: "604",
  VE: "862", UY: "858", EC: "218", BO: "068", PY: "600", CU: "192",
};

