/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RealmRouteImport } from './routes/realm'
import { Route as EconomyRouteImport } from './routes/economy'
import { Route as IndexRouteImport } from './routes/index'

const RealmRoute = RealmRouteImport.update({
  id: '/realm',
  path: '/realm',
  getParentRoute: () => rootRouteImport,
} as any)
const EconomyRoute = EconomyRouteImport.update({
  id: '/economy',
  path: '/economy',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/economy': typeof EconomyRoute
  '/realm': typeof RealmRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/economy': typeof EconomyRoute
  '/realm': typeof RealmRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/economy': typeof EconomyRoute
  '/realm': typeof RealmRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/economy' | '/realm'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/economy' | '/realm'
  id: '__root__' | '/' | '/economy' | '/realm'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EconomyRoute: typeof EconomyRoute
  RealmRoute: typeof RealmRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/realm': {
      id: '/realm'
      path: '/realm'
      fullPath: '/realm'
      preLoaderRoute: typeof RealmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/economy': {
      id: '/economy'
      path: '/economy'
      fullPath: '/economy'
      preLoaderRoute: typeof EconomyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EconomyRoute: EconomyRoute,
  RealmRoute: RealmRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
