/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as EconomyRouteImport } from './routes/economy'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WorkshopBuildingIdRouteImport } from './routes/workshop.$buildingId'
import { Route as SanctumInvocationRouteImport } from './routes/sanctum.invocation'
import { Route as PledgeSoulIdRouteImport } from './routes/pledge.$soulId'
import { Route as ChamberHighCouncilRouteImport } from './routes/chamber.high-council'
import { Route as ChamberSoulIdRouteImport } from './routes/chamber.$soulId'
import { Route as SanctumChamberSoulIdRouteImport } from './routes/sanctum.chamber.$soulId'
import { Route as ApiPublicWorkshopIntakeRouteImport } from './routes/api/public/workshop-intake'
import { Route as ApiPublicSyncVeniceRegistryRouteImport } from './routes/api/public/sync-venice-registry'
import { Route as ApiPublicDispatchScheduledMailRouteImport } from './routes/api/public/dispatch-scheduled-mail'

const EconomyRoute = EconomyRouteImport.update({
  id: '/economy',
  path: '/economy',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkshopBuildingIdRoute = WorkshopBuildingIdRouteImport.update({
  id: '/workshop/$buildingId',
  path: '/workshop/$buildingId',
  getParentRoute: () => rootRouteImport,
} as any)
const SanctumInvocationRoute = SanctumInvocationRouteImport.update({
  id: '/sanctum/invocation',
  path: '/sanctum/invocation',
  getParentRoute: () => rootRouteImport,
} as any)
const PledgeSoulIdRoute = PledgeSoulIdRouteImport.update({
  id: '/pledge/$soulId',
  path: '/pledge/$soulId',
  getParentRoute: () => rootRouteImport,
} as any)
const ChamberHighCouncilRoute = ChamberHighCouncilRouteImport.update({
  id: '/chamber/high-council',
  path: '/chamber/high-council',
  getParentRoute: () => rootRouteImport,
} as any)
const ChamberSoulIdRoute = ChamberSoulIdRouteImport.update({
  id: '/chamber/$soulId',
  path: '/chamber/$soulId',
  getParentRoute: () => rootRouteImport,
} as any)
const SanctumChamberSoulIdRoute = SanctumChamberSoulIdRouteImport.update({
  id: '/sanctum/chamber/$soulId',
  path: '/sanctum/chamber/$soulId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicWorkshopIntakeRoute = ApiPublicWorkshopIntakeRouteImport.update({
  id: '/api/public/workshop-intake',
  path: '/api/public/workshop-intake',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicSyncVeniceRegistryRoute =
  ApiPublicSyncVeniceRegistryRouteImport.update({
    id: '/api/public/sync-venice-registry',
    path: '/api/public/sync-venice-registry',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicDispatchScheduledMailRoute =
  ApiPublicDispatchScheduledMailRouteImport.update({
    id: '/api/public/dispatch-scheduled-mail',
    path: '/api/public/dispatch-scheduled-mail',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/economy': typeof EconomyRoute
  '/chamber/$soulId': typeof ChamberSoulIdRoute
  '/chamber/high-council': typeof ChamberHighCouncilRoute
  '/pledge/$soulId': typeof PledgeSoulIdRoute
  '/sanctum/invocation': typeof SanctumInvocationRoute
  '/workshop/$buildingId': typeof WorkshopBuildingIdRoute
  '/api/public/dispatch-scheduled-mail': typeof ApiPublicDispatchScheduledMailRoute
  '/api/public/sync-venice-registry': typeof ApiPublicSyncVeniceRegistryRoute
  '/api/public/workshop-intake': typeof ApiPublicWorkshopIntakeRoute
  '/sanctum/chamber/$soulId': typeof SanctumChamberSoulIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/economy': typeof EconomyRoute
  '/chamber/$soulId': typeof ChamberSoulIdRoute
  '/chamber/high-council': typeof ChamberHighCouncilRoute
  '/pledge/$soulId': typeof PledgeSoulIdRoute
  '/sanctum/invocation': typeof SanctumInvocationRoute
  '/workshop/$buildingId': typeof WorkshopBuildingIdRoute
  '/api/public/dispatch-scheduled-mail': typeof ApiPublicDispatchScheduledMailRoute
  '/api/public/sync-venice-registry': typeof ApiPublicSyncVeniceRegistryRoute
  '/api/public/workshop-intake': typeof ApiPublicWorkshopIntakeRoute
  '/sanctum/chamber/$soulId': typeof SanctumChamberSoulIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/economy': typeof EconomyRoute
  '/chamber/$soulId': typeof ChamberSoulIdRoute
  '/chamber/high-council': typeof ChamberHighCouncilRoute
  '/pledge/$soulId': typeof PledgeSoulIdRoute
  '/sanctum/invocation': typeof SanctumInvocationRoute
  '/workshop/$buildingId': typeof WorkshopBuildingIdRoute
  '/api/public/dispatch-scheduled-mail': typeof ApiPublicDispatchScheduledMailRoute
  '/api/public/sync-venice-registry': typeof ApiPublicSyncVeniceRegistryRoute
  '/api/public/workshop-intake': typeof ApiPublicWorkshopIntakeRoute
  '/sanctum/chamber/$soulId': typeof SanctumChamberSoulIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/economy'
    | '/chamber/$soulId'
    | '/chamber/high-council'
    | '/pledge/$soulId'
    | '/sanctum/invocation'
    | '/workshop/$buildingId'
    | '/api/public/dispatch-scheduled-mail'
    | '/api/public/sync-venice-registry'
    | '/api/public/workshop-intake'
    | '/sanctum/chamber/$soulId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/economy'
    | '/chamber/$soulId'
    | '/chamber/high-council'
    | '/pledge/$soulId'
    | '/sanctum/invocation'
    | '/workshop/$buildingId'
    | '/api/public/dispatch-scheduled-mail'
    | '/api/public/sync-venice-registry'
    | '/api/public/workshop-intake'
    | '/sanctum/chamber/$soulId'
  id:
    | '__root__'
    | '/'
    | '/economy'
    | '/chamber/$soulId'
    | '/chamber/high-council'
    | '/pledge/$soulId'
    | '/sanctum/invocation'
    | '/workshop/$buildingId'
    | '/api/public/dispatch-scheduled-mail'
    | '/api/public/sync-venice-registry'
    | '/api/public/workshop-intake'
    | '/sanctum/chamber/$soulId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EconomyRoute: typeof EconomyRoute
  ChamberSoulIdRoute: typeof ChamberSoulIdRoute
  ChamberHighCouncilRoute: typeof ChamberHighCouncilRoute
  PledgeSoulIdRoute: typeof PledgeSoulIdRoute
  SanctumInvocationRoute: typeof SanctumInvocationRoute
  WorkshopBuildingIdRoute: typeof WorkshopBuildingIdRoute
  ApiPublicDispatchScheduledMailRoute: typeof ApiPublicDispatchScheduledMailRoute
  ApiPublicSyncVeniceRegistryRoute: typeof ApiPublicSyncVeniceRegistryRoute
  ApiPublicWorkshopIntakeRoute: typeof ApiPublicWorkshopIntakeRoute
  SanctumChamberSoulIdRoute: typeof SanctumChamberSoulIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/economy': {
      id: '/economy'
      path: '/economy'
      fullPath: '/economy'
      preLoaderRoute: typeof EconomyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workshop/$buildingId': {
      id: '/workshop/$buildingId'
      path: '/workshop/$buildingId'
      fullPath: '/workshop/$buildingId'
      preLoaderRoute: typeof WorkshopBuildingIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sanctum/invocation': {
      id: '/sanctum/invocation'
      path: '/sanctum/invocation'
      fullPath: '/sanctum/invocation'
      preLoaderRoute: typeof SanctumInvocationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pledge/$soulId': {
      id: '/pledge/$soulId'
      path: '/pledge/$soulId'
      fullPath: '/pledge/$soulId'
      preLoaderRoute: typeof PledgeSoulIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chamber/high-council': {
      id: '/chamber/high-council'
      path: '/chamber/high-council'
      fullPath: '/chamber/high-council'
      preLoaderRoute: typeof ChamberHighCouncilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chamber/$soulId': {
      id: '/chamber/$soulId'
      path: '/chamber/$soulId'
      fullPath: '/chamber/$soulId'
      preLoaderRoute: typeof ChamberSoulIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sanctum/chamber/$soulId': {
      id: '/sanctum/chamber/$soulId'
      path: '/sanctum/chamber/$soulId'
      fullPath: '/sanctum/chamber/$soulId'
      preLoaderRoute: typeof SanctumChamberSoulIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/workshop-intake': {
      id: '/api/public/workshop-intake'
      path: '/api/public/workshop-intake'
      fullPath: '/api/public/workshop-intake'
      preLoaderRoute: typeof ApiPublicWorkshopIntakeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/sync-venice-registry': {
      id: '/api/public/sync-venice-registry'
      path: '/api/public/sync-venice-registry'
      fullPath: '/api/public/sync-venice-registry'
      preLoaderRoute: typeof ApiPublicSyncVeniceRegistryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/dispatch-scheduled-mail': {
      id: '/api/public/dispatch-scheduled-mail'
      path: '/api/public/dispatch-scheduled-mail'
      fullPath: '/api/public/dispatch-scheduled-mail'
      preLoaderRoute: typeof ApiPublicDispatchScheduledMailRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EconomyRoute: EconomyRoute,
  ChamberSoulIdRoute: ChamberSoulIdRoute,
  ChamberHighCouncilRoute: ChamberHighCouncilRoute,
  PledgeSoulIdRoute: PledgeSoulIdRoute,
  SanctumInvocationRoute: SanctumInvocationRoute,
  WorkshopBuildingIdRoute: WorkshopBuildingIdRoute,
  ApiPublicDispatchScheduledMailRoute: ApiPublicDispatchScheduledMailRoute,
  ApiPublicSyncVeniceRegistryRoute: ApiPublicSyncVeniceRegistryRoute,
  ApiPublicWorkshopIntakeRoute: ApiPublicWorkshopIntakeRoute,
  SanctumChamberSoulIdRoute: SanctumChamberSoulIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
